services:
  web:
    build: .
    ports:
      - "${PORT}:8080"
    environment:
      - PORT=8080
    read_only: true
    restart: on-failure:10
    volumes:
      - ./static:/app/static:ro
      - ./static/config.json:/app/static/config.json:ro
